### ISSUE TITLE
storage ?

### ISSUE THREAD

**Issue by joe-getcouragenow** [matthewhartstonge/hasher#3]
thanks for all the fosite work you have done. Its really helps for setting up auth and authz.

I am planning to build a GUI example in Flutter and Goi for others to use. If you want i can do it on your repo or ours.

https://git.sr.ht/~eliasnaur/gio/tree/master
Good Mirror: https://github.com/theclapp/gio-mirror
Issue: https://todo.sr.ht/~eliasnaur/gio

SO, I was wondering if your are going to use the mongodb storage with hasher and argon2 though 
Also i am planning to also setup a Badger DB storage that uses CRDT so you get automatic HA.

**Comment by matthewhartstonge** [comment]
Hi @joe-getcouragenow!

Thank you for you kind words 😄 

As for using fosite+storage(mongo)+hasher, that is exactly how we have composed our oauth server that we are using in production with over 100K users.
To do this you have to use the 'manual' compose option that takes in a hasher, as `composeAll` forces you down the path of bcrypt, which is great, but argon2id is recommeded.

So to bring it all together you would have something like this (modified from the example in fosite/README.md - apologies if it contains errors, I'm freehand copy+pasta'ing):

```go
package main

import argon2 "github.com/matthewhartstonge/hasher"
import "github.com/matthewhartstonge/storage/mongo"
import "github.com/ory/fosite/compose"
import log "github.com/sirupsen/logrus"

// This var block contains all the pre-configuration we need to configure to instatiate a fosite instance.
var (
  	// check the api docs of compose.Config for further configuration options
  	config = &compose.Config {
  	  	AccessTokenLifespan: time.Minute * 30,
		// ...
	}

	// storage binds in the fosite compliant mongo storage driver.
	storage= newMongo()

	// hasher provides a way to inject in a different hashing algorithm. defaults to bcrypt if nil.
	hasher = argon2.New(nil)

	// This secret is being used to sign access and refresh tokens as well as
	// authorization codes. It must be exactly 32 bytes long.
	secret = []byte("my super secret signing password")

	// This secret is being used to sign access and refresh tokens as well as
	// authorization codes. It must be exactly 32 bytes long.
	secret = []byte("my super secret signing password")

	// Provides us the key to use to generate RSA signed jwt tokens.
	privateKey, _ = rsa.GenerateKey(rand.Reader, 2048)
)

// newMongo inits a fosite-storage compatible mongo client.
func newMongo() *mongo.Store {
	store, err := mongo.NewDefaultStore()
	if err != nil {
		log.WithError(err).Fatal("error creating new store")
	}

	return  store
}

// oauth2Provider composes together all the requirements to configure our fosite instance.
var oauth2Provider = compose.Compose(
	config,
	storage,
	&CommonStrategy{
		CoreStrategy:               NewOAuth2HMACStrategy(config, secret, nil),
		OpenIDConnectTokenStrategy: NewOpenIDConnectStrategy(config, key),
		JWTStrategy: &jwt.RS256JWTStrategy{
			PrivateKey: key,
		},
	},
	hasher,

	OAuth2AuthorizeExplicitFactory,
	OAuth2AuthorizeImplicitFactory,
	OAuth2ClientCredentialsGrantFactory,
	OAuth2RefreshTokenGrantFactory,
	OAuth2ResourceOwnerPasswordCredentialsFactory,

	OpenIDConnectExplicitFactory,
	OpenIDConnectImplicitFactory,
	OpenIDConnectHybridFactory,
	OpenIDConnectRefreshFactory,

	OAuth2TokenIntrospectionFactory,

	OAuth2PKCEFactory,
)

// TODO: Implement OAuth2 handlers...
```
Hope that helps!


In terms of adding in a fosite compliant badgerDB backend, that would be cool!
Feel free to:
* fork this repo 
* create a branch off of development called `feature/badger`

I've just created a discord server if you would like to chat: https://discord.gg/PMMmP3

**Comment by joe-getcouragenow** [comment]
@matthewhartstonge 

Looks good. I will work on it now.. 

Here is the CRDT WAL lib i am basing my work on: https://github.com/StreamSpace/ants-db
Its based on IPFS and so designed to run in a NATed network environment and so not suitable. I need to work on a Server based one to replace RAFT still.
- 

Btw the discord invite fails for me !! Se screenshot.

![Screenshot 2020-06-24 at 11 55 15](https://user-images.githubusercontent.com/59567750/85534466-a78daa80-b611-11ea-993f-e2af41e2f74c.png)

**Comment by matthewhartstonge** [comment]
@joe-getcouragenow interesting!
Yeah, I've found raft can be very chatty over the network..

Sorry - discord tokens by default expire after 24 hours, try this one-time-use token instead: https://discord.gg/EmSrAA
